#!/usr/bin/env bash
case "$*" in
  *--show-sdk-path*)
    if [ -n "$SDK_PATH" ]; then
      echo "$SDK_PATH"
      exit 0
    fi
    ;;
  *--version*)
    echo "xcrun version 72."
    exit 0
    ;;
esac
if [ -x "$NATIVEPREFIX/bin/xcrun.real" ]; then
  exec -a xcrun "$NATIVEPREFIX/bin/xcrun.real" "$@"
fi
echo "xcrun: unsupported invocation: $*" >&2
exit 1
